config/routes.rb
Rails.application.routes.draw do

  # root 'home#index'
  # root 'demos#landing'

  root 'demos#landing'
  get 'demos/login'
  get 'demos/dashboard'
  get 'demos/index'
  get 'demos/form'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def init_breadcrumb(i18n)
    @breadcrumb = { title: I18n.t(:"#{i18n}"), list: [] }
    @breadcrumb[:list] << { href: demos_dashboard_path, text: I18n.t(:'demo.dashboard') }
  end
  def add_breadcrumb(path, i18n)
    @breadcrumb[:list] << { href: path, text: I18n.t(:"#{i18n}") }
  end

end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  layout :set_layout, only: [:landing, :login]
  def landing
  end

  def login
  end

  def dashboard
    init_breadcrumb('demo.dashboard')
  end

  def index
    init_breadcrumb('demo.index')
    add_breadcrumb(demos_index_path, 'demo.index')

    @list = [
      { id: '000', name: 'Alexander Pierce', email: 'root@mail.com', role: 'admin' },
      { id: '001', name: 'Lucy Johnson', email: 'lucyjhonson@mail.com', role: 'admin' },
      { id: '002', name: 'John Anderson', email: 'jhonanderson@mail.com', role: 'employee' },
      { id: '003', name: 'Sophie Turner', email: 'sophieturner@mail.com', role: 'technical' } ]
  end

  def form
    init_breadcrumb('demo.form')
    add_breadcrumb(demos_index_path, 'demo.form')
  end

  private

  def set_layout
    case action_name
    when 'login'
      'login'
    when 'landing'
      'outside'
    else
      'application' # Default layout
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inbox
    @inbox ||= [ { sender: 'Brad Diesel', avatar_path: 'dist/img/user1-128x128.jpg', message: 'Call me whenever you can...', time: '4 Hours', status_class: 'text-danger' },
      { sender: 'Brad Diesel', avatar_path: 'dist/img/user1-128x128.jpg', message: 'I got your message bro', time: '4 Hours', status_class: 'text-muted' },
      { sender: 'Nora Silvester', avatar_path: 'dist/img/user3-128x128.jpg', message: 'The subject goes here', time: '6 Hours', status_class: 'text-warning' } ]
  end
  def notifications
    @notifications ||= [
      { title: 'friend requests', amount: 4, time: '12 hours', icon_class: 'fas fa-users', path: '#' },
      { title: 'new reports', amount: 3, time: '8 hours', icon_class: 'fas fa-file', path: '#' }
    ]
  end
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/demos/dashboard.html.erb
<!-- Default box -->
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Title</h3>

    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
        <i class="fas fa-minus"></i>
      </button>
      <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
        <i class="fas fa-times"></i>
      </button>
    </div>
  </div>
  <div class="card-body">
    Start creating your amazing application!
    <hr>
    <div data-controller="hello"></div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    Footer
  </div>
  <!-- /.card-footer-->
</div>
<!-- /.card -->

app/views/demos/form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Form demo</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form >
          <div class="card-body">
            <div class="form-group">
              <label for="exampleInputName1">Full name</label>
              <input type="text" class="form-control" id="exampleInputName1" placeholder="Enter full name">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="exampleEmployeeId1">Employee ID</label>
              <input type="text" class="form-control" id="exampleEmployeeId1" placeholder="Enter employee ID">
            </div>
            <div class="form-group">
              <label for="exampleUserRole1">User role</label>
              <select id="exampleUserRole1" class="form-control">
                <option>Admin</option>
                <option>Employee</option>
                <option>Technical</option>
              </select>
            </div>
            <div class="form-group">
              <label for="exampleInputFile">Avatar</label>
              <div class="input-group">
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="exampleInputFile">
                  <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                </div>
                <!-- <div class="input-group-append"> -->
                <!-- <span class="input-group-text">Upload</span> -->
                <!-- </div> -->
              </div>
            </div>
            <div class="form-group">
              <label for="exampleNotes1">Employee ID</label>
              <textarea id="exampleNotes1" class="form-control" rows="3" placeholder="Enter notes"></textarea>
            </div>
            <div class="form-check">
              <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="exampleCheck1">
                <label class="custom-control-label" for="exampleCheck1">Active</label>
              </div>
            </div>
          </div>

        </form>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#modal-success">Submit</button>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/demos/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="navbar navbar-expand">
            <ul class="navbar-nav">
              <h3 class="card-title">Index demo</h3>
            </ul>
            <ul class="navbar-nav ml-auto">
              <a href="<%= demos_form_url %>" class="btn btn-tool btn-sm">
                <i class="fas fa-plus-circle"></i>
                New record
              </a>
            </ul>
          </div>
        </div>
        <!-- /.card-header -->
        <%= render "layouts/adminlte/modals" %>
        <div class="card-body table-responsive p-0">
          <table class="table table-head-fixed text-nowrap table-striped">
            <thead>
            <tr>
              <th>Employee ID</th>
              <th>Full name</th>
              <th>Email</th>
              <th>User role</th>
              <th>More</th>
            </tr>
            </thead>
            <tbody>
            <% @list.each do |element| %>
              <tr>
                <td><%= element[:id] %></td>
                <td><%= element[:name] %></td>
                <td><%= element[:email] %></td>
                <td><%= element[:role] %></td>
                <td>
                  <button  class="text-muted" data-toggle="modal" data-target="#modal-danger" style="background: none; border: none; margin: 0; padding: 0; cursor: pointer; outline: none;">
                    <i class="fas fa-trash" title="Destroy record"></i>
                  </button>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>

        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix" style="margin-top: 0%;">
          <!--          Showing 1 to 10 of 10 entries-->
          <div class="row">
            <div class="col-sm-12 col-md-5">
              <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing 1 to 10 of <%= @list.length %> entries</div>
            </div>
            <div class="col-sm-12 col-md-7">
              <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="paginate_button page-item previous disabled" id="example1_previous"><a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li>
                  <li class="paginate_button page-item active"><a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                  <li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="2" tabindex="0" class="page-link">2</a></li>
                  <li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="3" tabindex="0" class="page-link">3</a></li>
                  <li class="paginate_button page-item "><a href="#" aria-controls="example1" data-dt-idx="4" tabindex="0" class="page-link">4</a></li>
                  <li class="paginate_button page-item next" id="example1_next"><a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/demos/landing.html.erb
<!-- Navbar -->
<nav class="navbar navbar-light navbar-white" style="margin-bottom: -5%">
  <div class="container">
    <%= link_to root_path, class: "brand-link" do %>
      <%= image_tag("dist/img/AdminLTELogo.png", class: "brand-image img-circle elevation-3", style: 'opacity: .8')%>
    <% end %>
    <span class="brand-text font-weight-normal" style="color: dimgrey"><b>Admin</b>Gem</span>
    <div class="collapse navbar-collapse order-3" id="navbarCollapse">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
      </ul>
    </div>
    <!-- Right navbar links -->
    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
      <li class="nav-item dropdown">
        <a href="<%= demos_dashboard_path %>" type="button" class="btn nav-link btn-block" title="Home"><i class="fas fa-tachometer-alt"></i></a>
      </li>
      <li class="nav-item dropdown">
        <a href="<%= demos_login_path %>" type="button" class="btn nav-link btn-block" title="Sign in"><i class="fa fa-sign-in-alt"></i></a>
      </li>
    </ul>
  </div>
</nav>
<!-- /.navbar -->

<body class="hold-transition lockscreen">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="text-center">
    <p class="h1" style="font-size: 67px; color: dimgrey"><b>Admin</b>Gem</p>
    <p class="h3" style="color: grey"> AdminLTE 3 & Ruby 3 on Rails 7 </p>
    <p class="mb-1">
      <a href="<%= demos_dashboard_path %>">Go to Home Dashboard</a>
    </p>
  </div>
</div>
</body>
<hr>

<section class="content">
  <div class="container-fluid">

    <div class="row">
      <div class="col-md-12 col-lg-6 col-xl-4">
        <div class="card mb-2 bg-gradient-dark">
          <%= image_tag("dist/img/photo1.png", class: "card-img-top", alt: 'Dist Photo 1') %>
          <div class="card-img-overlay d-flex flex-column justify-content-end">
            <h5 class="card-title text-primary text-white">Card Title</h5>
            <p class="card-text text-white pb-2 pt-1">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor.</p>
            <a href="#" class="text-white">Last update 2 mins ago</a>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-lg-6 col-xl-4">
        <div class="card mb-2">
          <%= image_tag("dist/img/photo2.png", class: "card-img-top", alt: 'Dist Photo 2') %>
          <div class="card-img-overlay d-flex flex-column justify-content-center">
            <h5 class="card-title text-white mt-5 pt-2">Card Title</h5>
            <p class="card-text pb-2 pt-1 text-white">
              Lorem ipsum dolor sit amet, <br>
              consectetur adipisicing elit <br>
              sed do eiusmod tempor.
            </p>
            <a href="#" class="text-white">Last update 15 hours ago</a>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-lg-6 col-xl-4">
        <div class="card mb-2">
          <%= image_tag("dist/img/photo3.jpg", class: "card-img-top", alt: 'Dist Photo 3') %>
          <div class="card-img-overlay">
            <h5 class="card-title text-primary">Card Title</h5>
            <p class="card-text pb-1 pt-1 text-white">
              Lorem ipsum dolor <br>
              sit amet, consectetur <br>
              adipisicing elit sed <br>
              do eiusmod tempor. </p>
            <a href="#" class="text-primary">Last update 3 days ago</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>

app/views/demos/login.html.erb
<body class="hold-transition lockscreen">
<div class="lockscreen-wrapper">
  <div class="" style="color: dimgrey"> <!-- card card-outline card-primary -->
    <div class="card-header text-center">
      <p class="h1"><b>Admin</b>Gem</p>
    </div>
    <!-- .card-body -->
    <div class="card-body">
      <form action="<%= demos_dashboard_path %>" method="get">
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <button type="submit" class="btn btn-primary btn-block">Sign In</button>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <a href="#">I forgot my password</a>
          </div>
        </div>
      </form>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
</body>

app/views/home/index.html.erb
<!-- Default box -->
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Title</h3>

    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
        <i class="fas fa-minus"></i>
      </button>
      <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
        <i class="fas fa-times"></i>
      </button>
    </div>
  </div>
  <div class="card-body">
    Start creating your amazing application!
    <hr>
    <div data-controller="hello"></div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    Footer
  </div>
  <!-- /.card-footer-->
</div>
<!-- /.card -->

app/views/layouts/adminlte/_header.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= @breadcrumb[:title] %></h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <% @breadcrumb[:list].each do |crumb| %>
            <%# crumb[:active] = re %>
<!--            <li class="breadcrumb-item"><a href="#">Home</a></li>-->

            <%= link_to "#{crumb[:text]} ", crumb[:href], class: "breadcrumb-item #{crumb[:active]}" %>
          <% end %>
<!--          <li class="breadcrumb-item"><a href="#">Home</a></li>-->
<!--          <li class="breadcrumb-item active">Blank Page</li>-->
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>

app/views/layouts/adminlte/_navbar.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
<!--      <a href="../../index3.html" class="nav-link">Home</a>-->
      <a href="<%= root_path %>" class="nav-link"> <i class="nav-icon fas fa-helicopter"> </i> Landing</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="<%= demos_login_path %>" class="nav-link"> <i class="nav-icon fa fa-sign-in-alt"> </i> Login</a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Navbar Search -->
    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
              <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <% inbox.each do |msg| %>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <%= image_tag(msg[:avatar_path], class: "brand-image img-circle elevation-3", style: 'opacity: .8') %>
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  <%= msg[:sender] %>
                  <span class="float-right text-sm <%= msg[:status_class] %>"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm"><%= msg[:message] %></p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i><%= msg[:time] %></p>
              </div>
            </div>
            <!-- Message End -->
          </a>
        <% end %>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <% notifications_amount = @inbox.length + notifications.map { |notification| notification[:amount] }.sum %>
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge"> <%= notifications_amount %> </span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header"> <%= notifications_amount %> Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> <%= @inbox.length %> new messages
          <span class="float-right text-muted text-sm"><%= @inbox.first[:time] %></span>
        </a>
        <% @notifications.each do |ntf| %>
          <div class="dropdown-divider"></div>
          <a href="<%= ntf[:path] %>" class="dropdown-item">
            <i class="<%= ntf[:icon_class] %> mr-2"></i> <%= "#{ntf[:amount]} #{ntf[:title]}" %>
            <span class="float-right text-muted text-sm"><%= ntf[:time] %></span>
          </a>
        <% end %>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/layouts/adminlte/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
<!--  <a href="../../index3.html" class="brand-link">-->
  <a href="#" class="brand-link">
    <%= image_tag("dist/img/AdminLTELogo.png", class: "brand-image img-circle elevation-3", style: 'opacity: .8') %>
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <%= image_tag("dist/img/user2-160x160.jpg", class: "brand-image img-circle elevation-3", style: 'opacity: .8') %>
      </div>
      <div class="info">
        <a href="#" class="d-block">Alexander Pierce</a>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Dashboard
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="<%= demos_index_path %>" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Index</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="<%= demos_form_url %>" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Form</p>
              </a>
            </li>
          </ul>
        </li>
<!--        <li class="nav-item">-->
<!--          <a href="<%#= demos_login_path %>" class="nav-link">-->
<!--            <i class="nav-icon fa fa-sign-in-alt"></i>-->
<!--            <p>-->
<!--              Login-->
<!--              <span class="right badge badge-danger">New</span>-->
<!--            </p>-->
<!--          </a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a href="<%#= root_path %>" class="nav-link">-->
<!--            <i class="nav-icon fas fa-helicopter"></i>-->
<!--            <p>Landing</p>-->
<!--          </a>-->
<!--        </li>-->

        <li class="nav-header">MISCELLANEOUS</li>
        <li class="nav-item">
          <a href="https://adminlte.io/docs/3.1/" class="nav-link" target="_blank">
            <i class="nav-icon fas fa-file"></i>
            <p>Documentation</p>
          </a>
        </li>
        <li class="nav-header">MULTI LEVEL EXAMPLE</li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-circle"></i>
            <p>
              Level 1
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>
                  Level 2
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="#" class="nav-link">
                    <i class="far fa-dot-circle nav-icon"></i>
                    <p>Level 3</p>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminLTE 3 | Starter</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <!-- AdminLTE for demo purposes -->
  <%= javascript_include_tag 'dist/js/demo.js', "data-turbo-track": "reload", type: "module" %>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>

<body class="hold-transition sidebar-mini" data-turbo="false">
<!-- Site wrapper -->
<div class="wrapper">

  <%= render "layouts/adminlte/navbar" %>
  <%= render "layouts/adminlte/sidebar" %>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <%= render "layouts/adminlte/header" %>
    <%= render "layouts/adminlte/modals" %>
    <!-- Main content -->
    <section class="content">
      <%= yield %>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.2.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
</body>


</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AdminLTE 3 | Starter</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <!--    <meta name="turbo-visit-control" content="reload">-->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <!-- icheck bootstrap -->
<!--  <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">-->
  <!-- Theme style -->
<!--  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">-->
</head>
<body class="hold-transition login-page">
<div class="login-box" style="margin-top: -7%">
  <%= yield %>
</div>
<!-- /.login-box -->
</body>
</html>